site_name: My Docs

# Theme configuration
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Navigation structure
nav:
  - Fundamentals:
    - Object Oriented Programming: 1.Fundamentals/a_object_oriented_programming.md
    - Data Structures: 1.Fundamentals/b_data_structures.md
    - Algorithms: 1.Fundamentals/c_algorithms.md
    - Python: 1.Fundamentals/d_python.md
    - Java: 1.Fundamentals/e_java.md
  - Interviews:
    - Technical Interviews: 2.Interviews/a_technical_interviews.md

# Extensions for better markdown support
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes
  - toc:
      permalink: true
